# Generated by Django 5.0.1 on 2024-01-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
