# Generated by Django 4.0.1 on 2024-01-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_hosted_lobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hosted_lobby',
        ),
    ]
