# Generated by Django 4.0.1 on 2024-02-03 16:35

import backend.yandex_s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_hosted_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=backend.yandex_s3_storage.ClientDocsStorage(), upload_to='avatars/'),
        ),
    ]
