# Generated by Django 4.0.1 on 2024-02-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_alter_subscriber_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
                ('html_message', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='mailer.mail')),
                ('recipients', models.ManyToManyField(related_name='mailings', to='mailer.Subscriber')),
            ],
        ),
    ]
