# Generated by Django 4.0.1 on 2024-02-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_mail_mailing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='email',
            new_name='from_email',
        ),
    ]
