# Generated by Django 4.0.1 on 2024-02-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PROCESSING', max_length=10),
        ),
    ]
