# Generated by Django 5.0.1 on 2024-01-28 17:59

import apps.api.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='questpoint',
            name='image',
            field=models.ImageField(null=True, upload_to='quest_point_images/'),
        ),
        migrations.AlterField(
            model_name='questpoint',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_points', to='api.coordinate'),
        ),
        migrations.AlterField(
            model_name='questpoint',
            name='title',
            field=models.CharField(default='No title', max_length=255),
        ),
        migrations.CreateModel(
            name='PlayerLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questpoints', models.ManyToManyField(related_name='lobbies', to='api.questpoint')),
            ],
        ),
        migrations.CreateModel(
            name='LobbyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.api.models.game_image_file_path)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.playerlobby')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLobbyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerlobby')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playerlobby',
            name='players',
            field=models.ManyToManyField(related_name='lobbies', through='api.PlayerLobbyMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuestCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_quests', to='api.playerlobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_quests', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to='api.questtask')),
            ],
        ),
        migrations.AddField(
            model_name='questpoint',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_points', to='api.questtask'),
        ),
    ]
