# Generated by Django 4.0.1 on 2024-01-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_region_alter_playerlobby_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerlobby',
            name='host',
        ),
    ]
