# Generated by Django 4.0.1 on 2024-01-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_game_gamephoto_gamequesttask_gamesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tasks',
            field=models.ManyToManyField(through='api.GameQuestTask', to='api.QuestTask'),
        ),
    ]
