# Generated by Django 4.0.1 on 2024-02-01 22:22

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=8, max_length=8, prefix='', unique=True),
        ),
    ]
