# Generated by Django 4.0.1 on 2024-02-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_game_players_remove_game_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertaskcompletion',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed', to='api.gameuser'),
        ),
    ]
