# Generated by Django 4.0.1 on 2024-02-03 19:30

import apps.api.models
import backend.yandex_s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_player_gameuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamephoto',
            name='image',
            field=models.ImageField(storage=backend.yandex_s3_storage.ClientDocsStorage(), upload_to=apps.api.models.game_image_file_path),
        ),
        migrations.AlterField(
            model_name='questpoint',
            name='image',
            field=models.ImageField(null=True, storage=backend.yandex_s3_storage.ClientDocsStorage(), upload_to='quest_point_images/'),
        ),
    ]
