# Generated by Django 4.0.1 on 2024-02-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_game_started_at_alter_gamesettings_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='game', to='api.gamesettings'),
            preserve_default=False,
        ),
    ]
