# Generated by Django 4.0.1 on 2024-02-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='quest_points',
            field=models.ManyToManyField(related_name='routes', to='api.QuestPoint'),
        ),
    ]
