# Generated by Django 4.0.1 on 2024-02-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_route_quest_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertaskcompletion',
            name='game_photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.gamephoto'),
            preserve_default=False,
        ),
    ]
