# Generated by Django 4.0.1 on 2024-02-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_playertaskcompletion_game_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertaskcompletion',
            name='game_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gamephoto'),
        ),
    ]
