# Generated by Django 4.0.1 on 2024-02-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_playertaskcompletion_game_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertaskcompletion',
            name='game_photo',
        ),
        migrations.AddField(
            model_name='playertaskcompletion',
            name='photo',
            field=models.CharField(default=1, max_length=511),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playertaskcompletion',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
