# Generated by Django 4.0.1 on 2024-02-04 21:16

import apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_playertaskcompletion_game_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='secret',
            field=models.CharField(default=apps.api.models.generate_secret, max_length=10),
        ),
    ]
