# Generated by Django 4.0.1 on 2024-02-05 14:47

import apps.api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_gameuser_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='order_key',
            field=models.CharField(default=apps.api.models.generate_secret, max_length=10),
        ),
        migrations.AlterField(
            model_name='playertaskcompletion',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completion', to='api.gamephoto'),
        ),
    ]
