# Generated by Django 4.0.1 on 2024-02-09 13:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0024_gameuser_order_key_alter_playertaskcompletion_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameUser',
            new_name='Player',
        ),
    ]
