# Generated by Django 4.0.1 on 2024-03-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_questpoint_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettingsQuestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questpoint')),
            ],
        ),
        migrations.RemoveField(
            model_name='gamesettings',
            name='tasks',
        ),
        migrations.CreateModel(
            name='GameSettingsQuestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_quest_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.gamesettingsquestpoint')),
                ('quest_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questtask')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gamesettings')),
            ],
        ),
        migrations.AddField(
            model_name='gamesettingsquestpoint',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_quest_points', to='api.gamesettings'),
        ),
        migrations.AlterField(
            model_name='playertaskcompletion',
            name='game_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='api.gamesettingsquesttask'),
        ),
        migrations.DeleteModel(
            name='GameQuestTask',
        ),
    ]
